services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: onboarding-api-dev
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - .:/app
    command: npm run start:dev
